In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
kpidegr = pd.read_csv('raw_data_project.csv')

In [3]:
kpidegr.head()

         DAY       Node  Call Drop%  Call Drops
0  7/19/2021  CAZFHAAZZ        0.26        45.0
1  7/19/2021  CAZFHBAZZ        1.02       542.0
2  7/19/2021  CAZFHCAZZ        0.55       308.0
3  7/19/2021  CACAIAAZZ        0.70       342.0
4  7/19/2021  CACAIBAZZ        0.41       124.0

In [4]:
n = len(pd.unique(kpidegr['Node']))
  
print("No.of.unique values :", n)

No.of.unique values : 2547

In [5]:
nodedf= kpidegr.groupby(['Node'],as_index=False)

In [6]:
nodedf.get_group('CEICAHZ')

              DAY     Node  Call Drop%  Call Drops
85708  12/30/2021  CEICAHZ      4127.0       14.44
85728  12/31/2021  CEICAHZ      3018.0       12.46
85748    1/3/2022  CEICAHZ      2928.0       11.56
85768    1/4/2022  CEICAHZ      3856.0       13.73
85788    1/5/2022  CEICAHZ      3762.0       13.68
85808    1/6/2022  CEICAHZ      2972.0       11.43
85828    1/7/2022  CEICAHZ      3624.0       12.60
85848   1/10/2022  CEICAHZ      3828.0       13.34
85868   1/11/2022  CEICAHZ      3827.0       14.13
85888   1/12/2022  CEICAHZ      4224.0       15.60
85908   1/13/2022  CEICAHZ      5250.0       17.00
85928   1/14/2022  CEICAHZ      5806.0       17.54
85948   1/17/2022  CEICAHZ      4434.0       16.73
85968   1/18/2022  CEICAHZ      5102.0       16.25
85988   1/19/2022  CEICAHZ      5005.0       16.45
86008   1/20/2022  CEICAHZ      5358.0       16.29
86028   1/21/2022  CEICAHZ      5383.0       17.30
86048   1/24/2022  CEICAHZ      3681.0       13.02
86068   1/25/2022  CEICAHZ      3995.0       13.92
86088   1/26/2022  CEICAHZ      4366.0       15.16
86108   1/27/2022  CEICAHZ      4487.0       14.53
86128   1/28/2022  CEICAHZ      3971.0       13.76

In [7]:
for name, group in nodedf:
    plt.plot(group['DAY'],group['Call Drop%'])
    plt.grid(True)
    plt.axis('off')
    plt.savefig(name)
    plt.close()